"""add cities table

Revision ID: a8b1dffcb856
Revises: ab9e8531810a
Create Date: 2026-05-10 14:01:43.617987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a8b1dffcb856'
down_revision: Union[str, None] = 'ab9e8531810a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'cities',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('name', sa.String(100), nullable=False, index=True),
        sa.Column('country', sa.String(100), nullable=False),
        sa.Column('cost_index', sa.Integer(), nullable=False, server_default='2'),
        sa.Column('popularity', sa.Integer(), nullable=False, server_default='50'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
